/**
 * «افهم ما تتلو» — the translation of the meanings, shown with the ayah being
 * recited. This module is the data: which translations there are, getting the
 * one the reciter picked onto the device, and keeping it there. What it looks
 * like is `ui/meaning.ts`.
 *
 * **The source is QuranEnc.com, and its terms shape everything here.** The
 * text is shown exactly as published — never modified, added to or cut, and
 * a footnote is never dropped — and the translator, QuranEnc.com and the
 * version number go wherever a meaning is shown. Nothing here generates,
 * paraphrases or machine-translates a meaning: every word comes from a human
 * translation QuranEnc publishes.
 *
 * **Our own copy, fetched only when picked.** Seven translations are
 * regenerated by `Engine/scripts/fetch-translations.mjs` and served with the
 * site, under their content hash (`?v=`), out of the service worker's
 * precache — the translit.json arrangement. The reciter's one choice is then
 * kept in its OWN cache, `quran-meanings`, so it works offline: the service
 * worker only ever answers what it precached, and the HTTP cache is not
 * something to bet the setting on. The name deliberately does not start with
 * `prompter-` — every build's worker deletes the caches that do.
 *
 * **One translation on the device at a time.** When a new one has been stored
 * the others are deleted, and a newer version of the same one replaces it the
 * way a new model replaces the old (the model's URL carries its content
 * hash too). Offline with only an older version cached, the older one is
 * shown — its own version number in the attribution, so it says so.
 *
 * **Failure is never fatal and never half-done.** The setting changes only
 * once a translation is stored and has passed `checkMeaning`; until then the
 * app is exactly as it was.
 */
import type { Prefs } from "./prefs.js";

/** One translation the picker can offer. */
export interface MeaningEntry {
  key: string;
  /** ISO 639 code. */
  language: string;
  /** The language's name for itself — «اردو», "Français". */
  native: string;
  /** Its name in each interface language. */
  name: { en: string; ar: string };
  dir: "rtl" | "ltr";
  /** Who translated it, in each interface language. */
  translator: { en: string; ar: string };
  /** QuranEnc's version — null where they publish none (the Arabic tafsir). */
  version: string | null;
  /** When the text was retrieved, YYYY-MM-DD — recorded where QuranEnc publishes no version; never shown. */
  retrieved?: string;
  /** The file's size, for the picker — 0 when not known in advance. */
  bytes: number;
  /** Shipped with the site: its content hash. Absent: fetched live from QuranEnc. */
  hash?: string;
  /** QuranEnc's own title for it — carried by a live entry, which has no file yet. */
  title?: string;
}

export interface MeaningAyah {
  /** The translation, verbatim, footnote markers and all. */
  t: string;
  /** Its footnotes, verbatim — `[n] …` lines — when it has any. */
  f?: string;
}

/** A whole translation, as `fetch-translations.mjs` writes it. */
export interface MeaningFile {
  source: string;
  key: string;
  title: string;
  version: string | null;
  retrieved?: string;
  language: string;
  dir: "rtl" | "ltr";
  ayahs: Record<string, MeaningAyah>;
  /** Only on one fetched live from QuranEnc, which has no manifest entry to come back to. */
  native?: string;
  name?: { en: string; ar: string };
  translator?: { en: string; ar: string };
}

export const QURANENC_URL = "https://quranenc.com";
const API = "https://quranenc.com/api/v1";
const CACHE = "quran-meanings";
const SHIPPED = "/data/translations/";
/** A cache key only — nothing is served here. A live download is stored under it. */
const LIVE = "/data/translations/quranenc/";
/** Every ayah in the Quran. */
const AYAH_TOTAL = 6236;

/** Where an entry's file lives, and so the key it is cached under. */
function meaningUrl(e: MeaningEntry): string {
  return e.hash ? `${SHIPPED}${e.key}.json?v=${e.hash}` : `${LIVE}${e.key}.json?v=${encodeURIComponent(e.version ?? "")}`;
}

/**
 * A parsed file, or a refusal. The same check the script makes before it
 * writes, made again on what actually arrived: every ayah of THIS corpus,
 * once, with something to say. `counts[i]` is surah i+1's ayah count.
 */
export function checkMeaning(raw: unknown, key: string, counts: readonly number[]): MeaningFile {
  const f = raw as Partial<MeaningFile> | null;
  if (!f || typeof f !== "object" || !f.ayahs || typeof f.ayahs !== "object") throw new Error(`${key}: not a translation`);
  if (f.key !== key) throw new Error(`${key}: the file is ${String(f.key)}`);
  if (f.dir !== "rtl" && f.dir !== "ltr") throw new Error(`${key}: direction ${String(f.dir)}`);
  // Every file says which text it is: QuranEnc's version, or — where they
  // publish none — the date it was retrieved. One or the other must be there.
  const versioned = typeof f.version === "string" && f.version !== "";
  if (!versioned && !(f.version === null && /^\d{4}-\d{2}-\d{2}$/.test(f.retrieved ?? ""))) throw new Error(`${key}: no version`);
  let n = 0;
  for (let s = 1; s <= counts.length; s++) {
    for (let a = 1; a <= counts[s - 1]; a++) {
      const ayah = f.ayahs[`${s}:${a}`];
      if (!ayah || typeof ayah.t !== "string" || !ayah.t.trim()) throw new Error(`${key}: ${s}:${a} is missing`);
      n++;
    }
  }
  const total = Object.keys(f.ayahs).length;
  if (n !== AYAH_TOTAL || total !== AYAH_TOTAL) throw new Error(`${key}: ${total} ayahs for a Quran of ${AYAH_TOTAL}`);
  return f as MeaningFile;
}

// ---- the text and its footnotes ---------------------------------------------

/** A footnote: its marker as it stands in the text (`[2]`), or null for one with no number. */
export interface Note {
  mark: string | null;
  /** The note verbatim, its own `[2]` included. */
  text: string;
}

/** A run of the translation's text; `note` when the run is a marker that opens one. */
export interface Piece {
  text: string;
  note?: number;
}

/**
 * Split a translation into runs of text and the markers that open its notes —
 * WITHOUT changing a character: the runs joined are the translation, exactly.
 *
 * Only `[digits]` that a footnote actually carries is a marker. Square
 * brackets are also the translators' own: «[All] praise is [due] to Allāh»
 * is text, and must stay text.
 *
 * A note no marker points at — QuranEnc has one, Urdu 2:285, whose note has
 * no number — is listed in `unmarked`, and the panel offers it after the text.
 * A footnote is never dropped.
 */
export function parseMeaning(ayah: MeaningAyah): { pieces: Piece[]; notes: Note[]; unmarked: number[] } {
  const notes: Note[] = [];
  for (const line of (ayah.f ?? "").split("\n")) {
    const head = /^\[(\d+)\]/.exec(line);
    if (head) notes.push({ mark: head[0], text: line });
    else if (notes.length) notes[notes.length - 1].text += `\n${line}`;
    else if (line.trim()) notes.push({ mark: null, text: line });
  }
  const byMark = new Map(notes.flatMap((n, i) => (n.mark ? [[n.mark, i] as const] : [])));
  const pieces: Piece[] = [];
  const used = new Set<number>();
  let at = 0;
  for (const m of ayah.t.matchAll(/\[\d+\]/g)) {
    const i = byMark.get(m[0]);
    if (i === undefined) continue;
    if (m.index > at) pieces.push({ text: ayah.t.slice(at, m.index) });
    pieces.push({ text: m[0], note: i });
    used.add(i);
    at = m.index + m[0].length;
  }
  if (at < ayah.t.length) pieces.push({ text: ayah.t.slice(at) });
  const unmarked = notes.map((_, i) => i).filter((i) => !used.has(i));
  return { pieces, notes, unmarked };
}

// ---- the device's copy -------------------------------------------------------

/** The cache, or null where there is none (an insecure origin, a locked-down browser). */
async function openCache(): Promise<Cache | null> {
  try {
    return typeof caches === "undefined" ? null : await caches.open(CACHE);
  } catch {
    return null;
  }
}

/** Whatever is stored under this URL — this exact version, or with `anyVersion` the one kept. */
async function fromCache(url: string, anyVersion: boolean): Promise<string | null> {
  const cache = await openCache();
  try {
    const hit = await cache?.match(url, { ignoreSearch: anyVersion });
    return hit ? await hit.text() : null;
  } catch {
    return null;
  }
}

/** Put a download on the device. Nothing else is touched — see `evictAllBut`. */
async function store(e: MeaningEntry, text: string): Promise<void> {
  try {
    await (await openCache())?.put(meaningUrl(e), new Response(text, { headers: { "content-type": "application/json" } }));
  } catch {
    /* quota — it works this session, and downloads again next time */
  }
}

/**
 * Delete every translation on the device but this one. Only ever called for
 * the translation that is actually SHOWING: a download that lost to a newer
 * choice must not delete the copy the reciter went back to.
 */
async function evictAllBut(e: MeaningEntry): Promise<void> {
  const cache = await openCache();
  const url = meaningUrl(e);
  try {
    for (const req of (await cache?.keys()) ?? []) {
      const u = new URL(req.url);
      if (u.pathname + u.search !== url) await cache!.delete(req);
    }
  } catch {
    /* left for the next choice to clear */
  }
}

/** The keys of every translation on the device — for «على جهازك» in the picker. */
async function keysOnDevice(): Promise<Set<string>> {
  const cache = await openCache();
  const out = new Set<string>();
  try {
    for (const req of (await cache?.keys()) ?? []) {
      const m = /\/([a-z0-9_]+)\.json$/.exec(new URL(req.url).pathname);
      if (m) out.add(m[1]);
    }
  } catch {
    /* none, then */
  }
  return out;
}

/**
 * A shipped file from our own host, streamed so the picker can show progress.
 * The manifest knows the uncompressed size, which is what the stream counts —
 * Content-Length, where there is one, is the compressed size.
 */
async function download(e: MeaningEntry, onProgress: (f: number) => void, fetchImpl: typeof fetch): Promise<string> {
  const r = await fetchImpl(meaningUrl(e));
  if (!r.ok) throw new Error(`${e.key}: HTTP ${r.status}`);
  const reader = r.body?.getReader();
  if (!reader) return r.text();
  const decoder = new TextDecoder();
  let text = "";
  let got = 0;
  for (;;) {
    const { done, value } = await reader.read();
    if (done) break;
    got += value.length;
    text += decoder.decode(value, { stream: true });
    if (e.bytes > 0) onProgress(Math.min(1, got / e.bytes));
  }
  return text + decoder.decode();
}

/**
 * A translation the site does not ship, straight from QuranEnc — all 114
 * surahs, four at a time, checked ayah by ayah against the corpus and kept
 * verbatim, as the script does. CORS is open on their API.
 */
async function downloadLive(e: MeaningEntry, counts: readonly number[], onProgress: (f: number) => void, fetchImpl: typeof fetch): Promise<string> {
  const ayahs: Record<string, MeaningAyah> = {};
  const bodies: unknown[] = new Array(counts.length);
  let next = 1;
  let done = 0;
  // The first failure stops every worker. Left running, the other three went
  // on fetching the rest of the Quran after the failure was reported, and
  // their progress put «loading» back over the error, for good.
  let failed = false;
  await Promise.all(
    Array.from({ length: 4 }, async () => {
      try {
        while (!failed && next <= counts.length) {
          const s = next++;
          const r = await fetchImpl(`${API}/translation/sura/${e.key}/${s}`);
          if (!r.ok) throw new Error(`${e.key} surah ${s}: HTTP ${r.status}`);
          bodies[s - 1] = await r.json();
          if (!failed) onProgress(++done / counts.length);
        }
      } catch (err) {
        failed = true;
        throw err;
      }
    }),
  );
  bodies.forEach((body, i) => {
    const rows = (body as { result?: { sura: string; aya: string; translation: unknown; footnotes: unknown }[] })?.result;
    if (!Array.isArray(rows) || rows.length !== counts[i]) throw new Error(`${e.key} surah ${i + 1}: ${rows?.length ?? 0} ayahs`);
    rows.forEach((row, a) => {
      if (Number(row.sura) !== i + 1 || Number(row.aya) !== a + 1 || typeof row.translation !== "string") {
        throw new Error(`${e.key}: row ${a + 1} of surah ${i + 1} is ${row.sura}:${row.aya}`);
      }
      ayahs[`${i + 1}:${a + 1}`] = typeof row.footnotes === "string" && row.footnotes ? { t: row.translation, f: row.footnotes } : { t: row.translation };
    });
  });
  const file: MeaningFile = {
    source: "QuranEnc.com",
    key: e.key,
    title: e.title ?? e.translator.en,
    version: e.version,
    language: e.language,
    dir: e.dir,
    ayahs,
    native: e.native,
    name: e.name,
    translator: e.translator,
  };
  return JSON.stringify(file);
}

/** "English Translation - Noor International Center" → "Noor International Center". */
function translatorOf(title: string): string {
  const at = title.lastIndexOf(" - ");
  return at < 0 ? title.trim() : title.slice(at + 3).trim();
}

/** A language's name in `inLang` — the browser knows them all; the code if it does not. */
function languageName(iso: string, inLang: string): string {
  try {
    const name = new Intl.DisplayNames([inLang], { type: "language" }).of(iso) ?? iso;
    return name.charAt(0).toLocaleUpperCase(inLang) + name.slice(1);
  } catch {
    return iso;
  }
}

/** The entry a live download carries inside itself — there is no manifest to look it up in. */
function entryOf(file: MeaningFile): MeaningEntry {
  return {
    key: file.key,
    language: file.language,
    native: file.native ?? languageName(file.language, file.language),
    name: file.name ?? { en: languageName(file.language, "en"), ar: languageName(file.language, "ar") },
    dir: file.dir,
    translator: file.translator ?? { en: translatorOf(file.title), ar: translatorOf(file.title) },
    version: file.version,
    retrieved: file.retrieved,
    bytes: 0,
  };
}

// ---- the store ---------------------------------------------------------------

export type MeaningStatus =
  | { kind: "idle" }
  | { kind: "loading"; key: string; progress: number }
  | { kind: "failed"; key: string };

/**
 * What the settings and the panel both read: the translations on offer, the
 * one loaded, and a download in progress or failed.
 */
export class Meanings {
  /** What the site ships — the engine's manifest, baked in by vite.config.ts. */
  readonly shipped: readonly MeaningEntry[];
  /** QuranEnc's full list, once «لغات أخرى…» has asked for it; never the shipped ones twice. */
  more: MeaningEntry[] | null = null;
  /** The translation the reciter picked, loaded — null while off or not yet loaded. */
  file: MeaningFile | null = null;
  entry: MeaningEntry | null = null;
  status: MeaningStatus = { kind: "idle" };
  /** Which keys have a copy on the device. */
  onDevice = new Set<string>();
  private readonly prefs: Prefs;
  private readonly counts: readonly number[];
  private readonly fetchImpl: typeof fetch;
  private listeners: (() => void)[] = [];
  /** Bumped by every choice: a download that lands after a newer choice changes nothing. */
  private token = 0;

  constructor(prefs: Prefs, shipped: readonly MeaningEntry[], counts: readonly number[], fetchImpl: typeof fetch = (...a) => fetch(...a)) {
    this.prefs = prefs;
    this.shipped = shipped;
    this.counts = counts;
    this.fetchImpl = fetchImpl;
  }

  /** The translation the setting names — what the picker marks, loaded or not yet. */
  get chosen(): string | null {
    return this.prefs.meaning;
  }

  entryFor(key: string): MeaningEntry | null {
    return this.shipped.find((e) => e.key === key) ?? this.more?.find((e) => e.key === key) ?? (this.entry?.key === key ? this.entry : null);
  }

  /**
   * Pick a translation, or none. Resolves true once it is on the device and
   * showing; false if it failed or another choice overtook it. On failure
   * the setting and the meaning on screen stay exactly as they were.
   */
  async choose(key: string | null): Promise<boolean> {
    const token = ++this.token;
    if (key === null) {
      this.prefs.meaning = null;
      this.file = null;
      this.entry = null;
      this.status = { kind: "idle" };
      this.emit();
      return true;
    }
    if (this.file?.key === key && this.prefs.meaning === key) {
      this.status = { kind: "idle" };
      this.emit();
      return true;
    }
    const entry = this.entryFor(key);
    if (!entry) return false;
    this.status = { kind: "loading", key, progress: 0 };
    this.emit();
    try {
      const { file, current } = await this.obtain(entry, (p) => {
        if (token !== this.token) return;
        this.status = { kind: "loading", key, progress: p };
        this.emit();
      });
      if (token !== this.token) return false;
      this.file = file;
      this.entry = entry;
      this.status = { kind: "idle" };
      this.prefs.meaning = key;
      this.emit();
      if (current) await this.keepOnly(entry);
      return true;
    } catch (e) {
      console.warn(`[prompter] meaning ${key}: ${e instanceof Error ? e.message : String(e)}`);
      if (token === this.token) {
        this.status = { kind: "failed", key };
        this.emit();
      }
      return false;
    }
  }

  /**
   * At startup: load the translation already picked, from the device if it is
   * there. Quiet — no progress and no error on screen; a reciter who chose a
   * translation yesterday did not ask for a download today. If it cannot be
   * had, nothing shows, and the setting is kept for next time.
   */
  async restore(): Promise<void> {
    const key = this.prefs.meaning;
    void this.refreshDevice();
    if (!key) return;
    const token = ++this.token;
    const shipped = this.entryFor(key);
    try {
      let file: MeaningFile;
      let current = true;
      if (shipped) ({ file, current } = await this.obtain(shipped, () => undefined));
      else {
        // Fetched live on an earlier visit: the copy on the device is the only
        // record of what it is — and it is already the whole file.
        const text = await fromCache(`${LIVE}${key}.json`, true);
        if (!text) throw new Error("not on this device");
        file = checkMeaning(JSON.parse(text), key, this.counts);
      }
      if (token !== this.token) return;
      this.file = file;
      this.entry = shipped ?? entryOf(file);
      this.emit();
      if (current) await this.keepOnly(this.entry);
    } catch (e) {
      console.warn(`[prompter] meaning ${key} unavailable: ${e instanceof Error ? e.message : String(e)}`);
    }
  }

  /**
   * «لغات أخرى…»: QuranEnc's whole list, straight from their API, so any of
   * its translations can be downloaded to the device. The names come in both
   * interface languages; the language names, from the browser.
   */
  async loadMore(): Promise<boolean> {
    try {
      const get = async (loc: string) => {
        const r = await this.fetchImpl(`${API}/translations/list?localization=${loc}`);
        if (!r.ok) throw new Error(`list: HTTP ${r.status}`);
        const body = (await r.json()) as { translations?: Record<string, string>[] };
        if (!Array.isArray(body.translations)) throw new Error("list: no translations");
        return body.translations;
      };
      const [en, ar] = await Promise.all([get("en"), get("ar")]);
      const arTitle = new Map(ar.map((t) => [t.key, t.title]));
      const shipped = new Set(this.shipped.map((e) => e.key));
      this.more = en
        .filter((t) => !shipped.has(t.key) && /^[a-z0-9_]{1,64}$/.test(t.key) && (t.direction === "rtl" || t.direction === "ltr"))
        .map((t) => ({
          key: t.key,
          language: t.language_iso_code,
          native: languageName(t.language_iso_code, t.language_iso_code),
          name: { en: languageName(t.language_iso_code, "en"), ar: languageName(t.language_iso_code, "ar") },
          dir: t.direction as "rtl" | "ltr",
          translator: { en: translatorOf(t.title), ar: translatorOf(arTitle.get(t.key) ?? t.title) },
          version: t.version,
          bytes: 0,
          title: t.title,
        }));
      this.emit();
      return true;
    } catch (e) {
      console.warn(`[prompter] QuranEnc list: ${e instanceof Error ? e.message : String(e)}`);
      return false;
    }
  }

  /** How many languages QuranEnc offers, counting the shipped ones — once the list is in. */
  get languageCount(): number {
    return new Set([...this.shipped, ...(this.more ?? [])].map((e) => e.language)).size;
  }

  onChange(fn: () => void): () => void {
    this.listeners.push(fn);
    return () => {
      const i = this.listeners.indexOf(fn);
      if (i >= 0) this.listeners.splice(i, 1);
    };
  }

  /**
   * The device's copy of this exact version, else a download — checked, then
   * stored — else, offline, whatever older version is still on the device.
   * `current` is false for that older copy: it is what is showing, so nothing
   * may evict it in favour of a version that is not there.
   */
  private async obtain(entry: MeaningEntry, onProgress: (f: number) => void): Promise<{ file: MeaningFile; current: boolean }> {
    const url = meaningUrl(entry);
    const cached = await fromCache(url, false);
    if (cached) {
      try {
        return { file: checkMeaning(JSON.parse(cached), entry.key, this.counts), current: true };
      } catch {
        /* damaged — download it again */
      }
    }
    let text: string;
    try {
      text = entry.hash ? await download(entry, onProgress, this.fetchImpl) : await downloadLive(entry, this.counts, onProgress, this.fetchImpl);
    } catch (e) {
      const older = await fromCache(url, true);
      if (older) return { file: checkMeaning(JSON.parse(older), entry.key, this.counts), current: false };
      throw e;
    }
    const file = checkMeaning(JSON.parse(text), entry.key, this.counts);
    await store(entry, text);
    await this.refreshDevice();
    return { file, current: true };
  }

  /** One translation on the device: the one showing. */
  private async keepOnly(entry: MeaningEntry): Promise<void> {
    await evictAllBut(entry);
    await this.refreshDevice();
  }

  private async refreshDevice(): Promise<void> {
    this.onDevice = await keysOnDevice();
    this.emit();
  }

  private emit(): void {
    for (const fn of [...this.listeners]) fn();
  }
}
